const deptUtils = require('./deptUtils');
const employeeUtils = require('./employeeUtils');
const rolesUtils = require('./rolesUtils');
const utilsDict = new Map();
utilsDict.set("View all employees", employeeUtils.getAllEmployees);
utilsDict.set("Add employees", employeeUtils.addEmployee);
utilsDict.set("Update employee's role", employeeUtils.updateEmployeeRole);
utilsDict.set("Update employee's manager", employeeUtils.updateEmployeeManager);
utilsDict.set("View all employees of a manager", employeeUtils.getEmployeesByManager);
utilsDict.set("View all employees of a department", employeeUtils.getEmployeesByDept);
utilsDict.set("Delete employee", employeeUtils.deleteEmployee);
utilsDict.set("View all departments", deptUtils.getAllDepartments);
utilsDict.set("Add department", deptUtils.addDepartment);
utilsDict.set("Delete department", deptUtils.deleteDept);
utilsDict.set("View summed salaries of all employees in a department", deptUtils.getSalariesBydept);
utilsDict.set("View all roles", rolesUtils.getAllRoles);
utilsDict.set("Add role", rolesUtils.addRoles);
utilsDict.set("Delete role", rolesUtils.deleteRoles);

module.exports = utilsDict;
